<%@page errorPage="oops.jsp" import="jabadot.*,java.text.*,java.util.*" session="false" %>
<!-- 
  -- $Id: news.jsp,v 1.14 2001/07/21 14:10:06 ian Exp $
  --
  -- This is an included page, does not need header or user.
  -- Start of output generated by news.jsp.
  -->
<%@ taglib uri="/WEB-INF/jabadot.tld" prefix="jabadot"%>
<P>Here's the news we're following at
<% 
	Object[] date = { new Date() };
	out.println(MessageFormat.format(
	   "{0,time} on {0,date}", date));
 %>
<TABLE>
<jabadot:forAllArticles element="a">
<TR><TD WIDTH=100% id="Headline">
	<jsp:getProperty name="a" property="subject"/>
	</TD>
</TR>
<TR><TD WIDTH=100% id="Textbox">
	Submitted by 
	<jsp:getProperty name="a" property="from"/> - 
	<jsp:getProperty name="a" property="date"/>
	</TD>
</TR>
<!-- XXX TODO GET URL IF PRESENT -->
<TR><TD WIDTH=100%>
	<P><jsp:getProperty name="a" property="message"/></P>
</jabadot:forAllArticles>
</TABLE>
